Myproject/blog/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, CategoryList

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name = "home"),
    path('page/<int:page>', ArticleList.as_view(), name = "home"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name = "detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name = "category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name = "category")
]

Myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Myproject/blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter

# Create your models here.
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status = 'p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status = True)


class Category(models.Model):
    title = models.CharField(max_length = 200, verbose_name = "عنوان دسته بندی")
    slug = models.SlugField(max_length = 100, unique = True, verbose_name = "آدرس دسته بندی")
    status = models.BooleanField(default = True, verbose_name = "آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name = "پوزیشن")
    
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['position']
    
    def __str__(self):
        return self.title
    
    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
    )
    title = models.CharField(max_length = 200, verbose_name = "عنوان مقاله")
    slug = models.SlugField(max_length = 100, unique = True, verbose_name = "آدرس مقاله")
    category = models.ManyToManyField(Category, verbose_name = "دسته بندی", related_name = "articles")
    description = models.TextField(verbose_name = "محتوا")
    thumbnail = models.ImageField(upload_to = "images", verbose_name = "تصویر مقاله")
    publish = models.DateTimeField(default = timezone.now, verbose_name = "زمان انتشار")
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES, verbose_name = "وضعیت")
    
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish']
    
    def __str__(self):
        return self.title
    
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"
    
    # def category_published(self):
    #     return self.category.filter(status = True)
    
    objects = ArticleManager()

Myproject/blog/views.py
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse, JsonResponse, Http404
from .models import Article, Category

# Create your views here.
class ArticleList(ListView):
    queryset = Article.objects.published()
    paginate_by = 3


class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug = slug)
    
    
# def category(request, slug, page = 1):
#     category = get_object_or_404(Category.objects.active(), slug = slug)
#     articles_list = category.articles.published()
#     paginator = Paginator(articles_list, 3)
#     articles = paginator.get_page(page)
#     context = {
#         "category": category,
#         "articles": articles
#     }
#     return render(request, "blog/category.html", context)
class CategoryList(ListView):
    paginate_by = 3
    template_name = "blog/category_list.html"
    
    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug = slug)
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

Myproject/blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

Myproject/blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% block title %} | {{ object.title }}{% endblock %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{ object.thumbnail.url }}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{ object.title }}</h1>
            <time>{{ object.jpublish }}</time>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
          {{ object.description | linebreaks }}
        </div>
      </div>
    </div>
  </article>
{% endblock %}

Myproject/blog/templates/blog/article_list.html
{% extends 'blog/base.html' %}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ من</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{ article.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ article.description | truncatewords:30 }}
              </h3>
            </a>
            <p class="post-meta">منتشر شده توسط
              <a href="#">مهدی</a>
              {{ article.jpublish }}</p>
          </div>
          <div>
            {% for cat in article.category.active %}
              <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }}</a>
            {% endfor %}
          </div>
          <hr>
        {% endfor %}
        <!-- Pager -->
        {% if is_paginated %}
          <div class="clearfix pager-button">
            {% if page_obj.has_previous %}
              <a class="btn btn-primary float-right ml-3" href="{% url 'blog:home' page_obj.previous_page_number %}">پست های جدید &rarr;</a>
            {% endif %}
            {% if page_obj.has_next %}
              <a class="btn btn-primary float-right" href="{% url 'blog:home' page_obj.next_page_number %}">پست های قدیمی &larr;</a>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

Myproject/blog/templates/blog/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>وبلاگ من {% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      {% category_navbar %}
    </div>
  </nav>

  {% block main %}

  {% endblock %}

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

Myproject/blog/templates/blog/category.html
{% extends 'blog/base.html' %}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ من</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for article in category.articles.all %}
          <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{ article.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ article.description | truncatewords:30 }}
              </h3>
            </a>
            <p class="post-meta">منتشر شده توسط
              <a href="#">مهدی</a>
              {{ article.jpublish }}</p>
          </div>
          <div>
            {% for cat in article.category_published.all %}
              <a href="#">#{{ cat.title }}</a>
            {% endfor %}
          </div>
          <hr>
        {% endfor %}
        <!-- Pager -->
        <div class="clearfix pager-button">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Myproject/blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ من</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h3 class="alert alert-primary text-center">{{ category.title }}</h3>
        {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{ article.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ article.description | truncatewords:30 }}
              </h3>
            </a>
            <p class="post-meta">منتشر شده توسط
              <a href="#">مهدی</a>
              {{ article.jpublish }}</p>
          </div>
          <div>
            {% for cat in article.category_published.all %}
              <a href="#">#{{ cat.title }}</a>
            {% endfor %}
          </div>
          <hr>
        {% endfor %}
        <!-- Pager -->
        {% if is_paginated %}
          <div class="clearfix pager-button">
            {% if page_obj.has_previous %}
              <a class="btn btn-primary float-right ml-3" href="{% url 'blog:category' category.slug  page_obj.previous_page_number %}">پست های جدید &rarr;</a>
            {% endif %}
            {% if page_obj.has_next %}
              <a class="btn btn-primary float-right" href="{% url 'blog:category' category.slug  page_obj.next_page_number %}">پست های قدیمی &larr;</a>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

Myproject/blog/templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

Myproject/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %} | {{ article.title }}{% endblock %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{ article.thumbnail.url }}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{ article.title }}</h1>
            <span class="subheading">{{ article.jpublish }}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {{ article.description | linebreaks }}
        </div>
      </div>
    </div>
  </article>
{% endblock %}

Myproject/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ من</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for article in articles %}
          <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{ article.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ article.description | truncatewords:30 }}
              </h3>
            </a>
            <p class="post-meta">منتشر شده توسط
              <a href="#">مهدی</a>
              {{ article.jpublish }}</p>
          </div>
          <div>
            {% for cat in article.category.all %}
              <a href="#">#{{ cat.title }}</a>
            {% endfor %}
          </div>
          <hr>
        {% endfor %}
        <!-- Pager -->
        <div class="clearfix pager-button">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Myproject/blog/templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:home' %}">خانه</a>
      </li>
      {% for cat in category %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:category' cat.slug %}">{{ cat.title }}</a>
        </li>
      {% endfor %}
  </ul>
</div>